package com.app.ams.model;
// Generated Jan 19, 2018 9:11:33 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report", catalog = "attendance")
public class Report implements java.io.Serializable {

	private int id;
	private Attendance attendance;
	private Date date;
	private String day;
	private Date timeOfLogin;
	private Date timeOfLogout;
	private Integer workedHours;
	private String flag;
	private Date lastUpdated;
	private String comments;

	public Report() {
	}

	public Report(int id) {
		this.id = id;
	}

	public Report(int id, Attendance attendance, Date date, String day, Date timeOfLogin, Date timeOfLogout,
			Integer workedHours, String flag, Date lastUpdated, String comments) {
		this.id = id;
		this.attendance = attendance;
		this.date = date;
		this.day = day;
		this.timeOfLogin = timeOfLogin;
		this.timeOfLogout = timeOfLogout;
		this.workedHours = workedHours;
		this.flag = flag;
		this.lastUpdated = lastUpdated;
		this.comments = comments;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Attendance getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Attendance attendance) {
		this.attendance = attendance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "day", length = 45)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time_of_login", length = 8)
	public Date getTimeOfLogin() {
		return this.timeOfLogin;
	}

	public void setTimeOfLogin(Date timeOfLogin) {
		this.timeOfLogin = timeOfLogin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time_of_logout", length = 8)
	public Date getTimeOfLogout() {
		return this.timeOfLogout;
	}

	public void setTimeOfLogout(Date timeOfLogout) {
		this.timeOfLogout = timeOfLogout;
	}

	@Column(name = "worked_hours")
	public Integer getWorkedHours() {
		return this.workedHours;
	}

	public void setWorkedHours(Integer workedHours) {
		this.workedHours = workedHours;
	}

	@Column(name = "flag", length = 45)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "comments", length = 1000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
